# Configuration values for deploying the Blacknet application using Helm

replicaCount: 1

image:
  repository: blacknet
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: [] 

resources: {}
  
nodeSelector: {}

tolerations: []

affinity: {}