scrape_configs:
  - job_name: 'quantum-engine'
    static_configs:
      - targets: ['localhost:9090']  # Replace with your actual target addresses
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '$1'
        regex: '(.*):.*'  # Extract the instance name from the address
```